apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: n-search
spec:
  version: "v0.0.1-alpha1"
  homepage: https://github.com/adeniyistephen/kubectl-plugin
  # 'shortDescription' explains what the plugin does in only a few words
  shortDescription: "Search for resources in Kubernetes cluster with namespace names"
  description: |
    Thanks
  # 'platforms' specify installation methods for various platforms (os/arch)
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/adeniyistephen/kubectl-plugin/archive/refs/tags/v0.0.1-alpha1.tar.gz
    # 'sha256' is the sha256sum of the url above
    sha256: 31887a082acfa936d4240c13aad3e3d10bbb4a2769fc5caa7fa1d41283f5df69
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "/kubectl-plugin*/*.sh"
      to: "."